#!/bin/bash
echo "=============================="
echo " Jenkins CI Build Started"
echo "=============================="
echo "Build Date: $(date)"
echo "Build Number: $BUILD_NUMBER"
echo "Job Name: $JOB_NAME"
echo "Workspace: $WORKSPACE"
echo ""
echo "Running application tests..."
sleep 2
echo "Test 1 PASSED - Hello World Function"
echo "Test 2 PASSED - Environment Variables"
echo "Test 3 PASSED - Date/Time Check"
echo ""
echo "=============================="
echo " All Tests PASSED!"
echo " Build Successful!"
echo "=============================="
